apiVersion: v1
entries:
  elasticsearch:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2025-07-23T17:40:30.912861577+02:00"
    description: Official Elastic helm chart for Elasticsearch
    digest: 8a5e70ec72dc480c8a01b079bf7240722da7d017f5683178e23a745d418448ba
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - https://nico-daco.github.io/kestra-helm-charts/charts/elasticsearch-8.5.1.tgz
    version: 8.5.1
  kafka:
  - annotations:
      category: Infrastructure
      images: |
        - name: jmx-exporter
          image: docker.io/bitnami/jmx-exporter:1.0.1-debian-12-r9
        - name: kafka
          image: docker.io/bitnami/kafka:3.8.1-debian-12-r0
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.31.2-debian-12-r3
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r32
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 3.8.1
    created: "2025-07-23T17:40:30.921988379+02:00"
    dependencies:
    - condition: zookeeper.enabled
      name: zookeeper
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 13.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache Kafka is a distributed streaming platform designed to build
      real-time pipelines and can be used as a message broker or as a replacement
      for a log aggregation solution for big data applications.
    digest: fe2444fe2e4c202b08ab8aea3cde642fe06fbabd2c93badedcfef148054c1c57
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/kafka/img/kafka-stack-220x234.png
    keywords:
    - kafka
    - zookeeper
    - streaming
    - producer
    - consumer
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: kafka
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/kafka
    urls:
    - https://nico-daco.github.io/kestra-helm-charts/charts/kafka-30.1.8.tgz
    version: 30.1.8
  minio:
  - annotations:
      category: Infrastructure
      images: |
        - name: minio
          image: docker.io/bitnami/minio:2024.12.18-debian-12-r1
        - name: minio-client
          image: docker.io/bitnami/minio-client:2024.11.21-debian-12-r3
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r35
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2024.12.18
    created: "2025-07-23T17:40:30.924927709+02:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MinIO(R) is an object storage server, compatible with Amazon S3 cloud
      storage service, mainly used for storing unstructured data (such as photos,
      videos, log files, etc.).
    digest: 9e956ffbcbf2617351904056a89d55c1c9e3b0a42b149c210a88b4665084ef23
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/minio/img/minio-stack-220x234.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: minio
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/minio
    urls:
    - https://nico-daco.github.io/kestra-helm-charts/charts/minio-14.10.5.tgz
    version: 14.10.5
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r30
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-12-r43
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.4.0-debian-12-r14
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.4.0
    created: "2025-07-23T17:40:30.930175171+02:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 6537de714df16f71c720921bd0ad8fad90bb01525fb3aacff3503781de3f9f8b
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://nico-daco.github.io/kestra-helm-charts/charts/postgresql-15.5.38.tgz
    version: 15.5.38
generated: "2025-07-23T17:40:30.911247839+02:00"
